# Generated by Django 5.2.4 on 2025-07-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/", verbose_name="Изображение"
            ),
        ),
    ]
