# Generated by Django 5.2.4 on 2025-08-23 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_products_created_at_alter_products_updated_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="products",
            options={
                "ordering": ["name", "purchase_price"],
                "permissions": [
                    ("can_unpublish_product", "Может отменять публикацию продукта")
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.AddField(
            model_name="products",
            name="is_published",
            field=models.BooleanField(
                default=False,
                help_text="Указывает, опубликован ли товар на сайте. По умолчанию — не опубликован.",
                verbose_name="Опубликовано",
            ),
        ),
        migrations.AddField(
            model_name="products",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owners_product",
                to=settings.AUTH_USER_MODEL,
                verbose_name="продукты пользователя",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(
                help_text="Краткое описание категории (до 300 символов).",
                max_length=300,
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="Введите название категории, например: 'Электроника', 'Мебель'.",
                max_length=100,
                verbose_name="Наименование",
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="category",
            field=models.ForeignKey(
                help_text="Выберите категорию, к которой относится товар.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="catalog.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Дата и время автоматического создания записи.",
                null=True,
                verbose_name="Дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="description",
            field=models.TextField(
                help_text="Краткое описание товара (до 300 символов).",
                max_length=300,
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите изображение товара (опционально).",
                null=True,
                upload_to="images/",
                verbose_name="Изображение",
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="name",
            field=models.CharField(
                help_text="Введите название товара (например, 'Смартфон Samsung').",
                max_length=100,
                verbose_name="Наименование",
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="purchase_price",
            field=models.IntegerField(
                help_text="Укажите цену товара (не может быть отрицательной).",
                verbose_name="Цена за покупку",
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Автоматически обновляется при каждом изменении.",
                null=True,
                verbose_name="Дата последнего обновления",
            ),
        ),
    ]
